# this is the docker config for the local instance, docker . use prisma to connect.
version: '3.8'

services:
 postgres:
   image:  postgres:15
   container_name: letvana_ postgres
 environment:
  POSTGRES_DB: letvana_dev
  POSTGRES_USER : dev_user
  POSTGRES_PASSWORD:  dev_password123
ports:
 - "5432:5432"
volumes:
 - postgres_data:/var/lib/postgresql/data
 - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
restart: unless-stopped


Volumes:
  postgres_data;


